<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
		<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>full</TrimMode>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="BlazorWasmPreRendering.Build" Version="8.0.0" />
		<PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
		<PackageReference Include="Humanizer.Core" Version="3.0.10" />
		<PackageReference Include="Humanizer.Core.es" Version="3.0.10" />
		<PackageReference Include="Humanizer.Core.pt" Version="3.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10">
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.10" />
		<PackageReference Include="MudBlazor" Version="9.7.0" />
		<PackageReference Include="Sentry.AspNetCore.Blazor.WebAssembly" Version="6.6.0" />
		<PackageReference Include="Toolbelt.Blazor.PWA.Updater" Version="3.2.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\WS.Shared\WS.Shared.csproj" />
		<TrimmerRootAssembly Include="WS.WEB" />
		<TrimmerRootAssembly Include="WS.Shared" />
	</ItemGroup>
	<ItemGroup>
		<ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Modules\Help\Resources\Translations.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Translations.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="Translations\Button.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Button.resx</DependentUpon>
		</Compile>
		<Compile Update="Translations\Description.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Description.resx</DependentUpon>
		</Compile>
		<Compile Update="Translations\Module\Auth.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Auth.resx</DependentUpon>
		</Compile>
		<Compile Update="Translations\Module\Help.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Help.resx</DependentUpon>
		</Compile>
		<Compile Update="Translations\Module\Legal.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Legal.resx</DependentUpon>
		</Compile>
		<Compile Update="Translations\Notification.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Notification.resx</DependentUpon>
		</Compile>
		<Compile Update="Translations\Title.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Title.resx</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="Modules\Help\Resources\Translations.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Translations.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Translations\Button.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Button.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Translations\Description.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Description.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Translations\Module\Auth.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Auth.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Translations\Module\Help.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Help.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Translations\Module\Legal.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Legal.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Translations\Notification.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Notification.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Translations\Title.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Title.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	<PropertyGroup>
		<BlazorWasmPrerenderingMode>Static</BlazorWasmPrerenderingMode>
		<BlazorWasmPrerenderingUrlPathToExplicitFetch>/en</BlazorWasmPrerenderingUrlPathToExplicitFetch>
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
		<CurrentDate>$([System.DateTime]::Now.ToString(yyyy.MM.dd))</CurrentDate>
	</PropertyGroup>
	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<WriteLinesToFile File="$(ProjectDir)wwwroot\js\app-version.js" Lines="window.appVersion = '$(CurrentDate)';" Overwrite="true" />
	</Target>
</Project>
