//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.WEB.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WS.WEB.Translations.Notification", typeof(Notification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdBlocker detected. Please consider whitelisting our app to support us. Thank you!.
        /// </summary>
        internal static string AdBlockerDetected {
            get {
                return ResourceManager.GetString("AdBlockerDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform is still under development. Some modules may be partially functional or not yet implemented..
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore our other amazing apps:.
        /// </summary>
        internal static string CheckOurApps {
            get {
                return ResourceManager.GetString("CheckOurApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation. Please try again..
        /// </summary>
        internal static string CustomVisibilityInvalid {
            get {
                return ResourceManager.GetString("CustomVisibilityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string CustomVisibilityLoading {
            get {
                return ResourceManager.GetString("CustomVisibilityLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not available.
        /// </summary>
        internal static string CustomVisibilityNoData {
            get {
                return ResourceManager.GetString("CustomVisibilityNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Website Notice.
        /// </summary>
        internal static string ExternalWebsiteNotice {
            get {
                return ResourceManager.GetString("ExternalWebsiteNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for news....
        /// </summary>
        internal static string FeatureUnavailableDescription {
            get {
                return ResourceManager.GetString("FeatureUnavailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under development.
        /// </summary>
        internal static string FeatureUnavailableMessage {
            get {
                return ResourceManager.GetString("FeatureUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled!.
        /// </summary>
        internal static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully!.
        /// </summary>
        internal static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation in progress. Please wait....
        /// </summary>
        internal static string OperationProgress {
            get {
                return ResourceManager.GetString("OperationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE NOW.
        /// </summary>
        internal static string PWAUpdaterButton {
            get {
                return ResourceManager.GetString("PWAUpdaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available.
        /// </summary>
        internal static string PWAUpdaterText {
            get {
                return ResourceManager.GetString("PWAUpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
