//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WS.WEB.Resources.GlobalTranslations", typeof(GlobalTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or check out our other apps:.
        /// </summary>
        public static string CheckOurApps {
            get {
                return ResourceManager.GetString("CheckOurApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation. Please try again..
        /// </summary>
        public static string CustomVisibilityInvalid {
            get {
                return ResourceManager.GetString("CustomVisibilityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CustomVisibilityLoading {
            get {
                return ResourceManager.GetString("CustomVisibilityLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not available.
        /// </summary>
        public static string CustomVisibilityNoData {
            get {
                return ResourceManager.GetString("CustomVisibilityNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover our other products.
        /// </summary>
        public static string DiscoverProducts {
            get {
                return ResourceManager.GetString("DiscoverProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for news....
        /// </summary>
        public static string FeatureUnavailableDescription {
            get {
                return ResourceManager.GetString("FeatureUnavailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under development.
        /// </summary>
        public static string FeatureUnavailableMessage {
            get {
                return ResourceManager.GetString("FeatureUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled!.
        /// </summary>
        public static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully!.
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE NOW.
        /// </summary>
        public static string PWAUpdaterButton {
            get {
                return ResourceManager.GetString("PWAUpdaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available.
        /// </summary>
        public static string PWAUpdaterText {
            get {
                return ResourceManager.GetString("PWAUpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search terms returned no results. Please change them and try again..
        /// </summary>
        public static string SearchReturnedNothing {
            get {
                return ResourceManager.GetString("SearchReturnedNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all items.
        /// </summary>
        public static string SeeAllItems {
            get {
                return ResourceManager.GetString("SeeAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review and help us reach more users:.
        /// </summary>
        public static string WriteReviewSubtitle {
            get {
                return ResourceManager.GetString("WriteReviewSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the store link doesn&apos;t work, try going directly to the website..
        /// </summary>
        public static string WriteReviewSubtitleStore {
            get {
                return ResourceManager.GetString("WriteReviewSubtitleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to help {0} grow?.
        /// </summary>
        public static string WriteReviewTitle {
            get {
                return ResourceManager.GetString("WriteReviewTitle", resourceCulture);
            }
        }
    }
}
